export const AUTHENTICATION_FAILED: string = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_SUCCEED: string = 'AUTHENTICATION_SUCCEED';
export const GET_CURRENT_USERNAME: string = 'GET_CURRENT_USERNAME';
export const LOGOUT: string = 'LOGOUT';
export const PROGRAMS_BY_UNIVERSITY: string = 'PROGRAMS_BY_UNIVERSITY'
export const SELECT_PROGRAM: string = 'SELECT_PROGRAM'