export const AUTHENTICATION_FAILED: string = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_SUCCEED: string = 'AUTHENTICATION_SUCCEED';
export const GET_CURRENT_USERNAME: string = 'GET_CURRENT_USERNAME';
export const LOGOUT: string = 'LOGOUT';